name: Build and Deploy via FTP

# Kích hoạt workflow khi có code mới được push lên nhánh 'main'
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Chạy trên máy chủ ảo của GitHub

    steps:
      # Bước 1: Lấy code từ kho về
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt môi trường Node.js (bạn có thể đổi phiên bản)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: VancyAdmin/package-lock.json
      # Bước 3: Cài đặt các gói cần thiết
      - name: Install dependencies
        run: npm install

      # Bước 4: Build dự án React
      - name: Build project
        run: npm run build # Lệnh này tạo ra thư mục 'build'

      # Bước 5: Upload thư mục 'build' lên hosting qua FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./VancyAdmin/dist/ # Thư mục nguồn để upload
          server-dir: /domains/admin.nguyenlieuvancy.shop/public_html/ # <-- THAY ĐỔI ĐƯỜNG DẪN NÀY
